# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/chiron/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/xiaomi/chiron/proprietary/etc/camera/camera_config.xml:system/etc/camera/camera_config.xml \
    vendor/xiaomi/chiron/proprietary/etc/camera/chiron_imx386_semco_chromatix.xml:system/etc/camera/chiron_imx386_semco_chromatix.xml \
    vendor/xiaomi/chiron/proprietary/etc/camera/chiron_ov5675_primax_chromatix.xml:system/etc/camera/chiron_ov5675_primax_chromatix.xml \
    vendor/xiaomi/chiron/proprietary/etc/camera/chiron_ov5675_qtech_chromatix.xml:system/etc/camera/chiron_ov5675_qtech_chromatix.xml \
    vendor/xiaomi/chiron/proprietary/etc/elliptic_sensor.xml:system/etc/elliptic_sensor.xml \
    vendor/xiaomi/chiron/proprietary/etc/firmware/tas2559_s_uCDSP.bin:system/etc/firmware/tas2559_s_uCDSP.bin \
    vendor/xiaomi/chiron/proprietary/etc/firmware/tas2559_uCDSP.bin:system/etc/firmware/tas2559_uCDSP.bin \
    vendor/xiaomi/chiron/proprietary/etc/jdi_fhd_video_dsi_panel_ct.xml:system/etc/jdi_fhd_video_dsi_panel_ct.xml \
    vendor/xiaomi/chiron/proprietary/lib64/libnotifyaudiohal.so:system/lib64/libnotifyaudiohal.so \
    vendor/xiaomi/chiron/proprietary/lib64/libultrasound.so:system/lib64/libultrasound.so \
    vendor/xiaomi/chiron/proprietary/vendor/bin/adsprpcd:system/vendor/bin/adsprpcd \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Bluetooth_cal.acdb:system/vendor/etc/acdbdata/ChironS/Forte_ChironS_Bluetooth_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_General_cal.acdb:system/vendor/etc/acdbdata/ChironS/Forte_ChironS_General_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Global_cal.acdb:system/vendor/etc/acdbdata/ChironS/Forte_ChironS_Global_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Handset_cal.acdb:system/vendor/etc/acdbdata/ChironS/Forte_ChironS_Handset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Hdmi_cal.acdb:system/vendor/etc/acdbdata/ChironS/Forte_ChironS_Hdmi_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Headset_cal.acdb:system/vendor/etc/acdbdata/ChironS/Forte_ChironS_Headset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Speaker_cal.acdb:system/vendor/etc/acdbdata/ChironS/Forte_ChironS_Speaker_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_workspaceFile.qwsp:system/vendor/etc/acdbdata/ChironS/Forte_ChironS_workspaceFile.qwsp \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:system/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:system/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:system/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:system/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:system/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:system/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:system/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_workspaceFile.qwsp:system/vendor/etc/acdbdata/Forte/Forte_workspaceFile.qwsp \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:system/vendor/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/sensors/hals.conf:system/vendor/etc/sensors/hals.conf \
    vendor/xiaomi/chiron/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:system/vendor/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/chiron/proprietary/vendor/etc/thermal-engine-8998.conf:system/vendor/etc/thermal-engine-8998.conf \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libSonyIMX386PdafLibrary.so:system/vendor/lib/libSonyIMX386PdafLibrary.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libactuator_chiron_imx386_ak7372_semco.so:system/vendor/lib/libactuator_chiron_imx386_ak7372_semco.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libadsp_default_listener.so:system/vendor/lib/libadsp_default_listener.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libadsp_hvx_callback_skel.so:system/vendor/lib/libadsp_hvx_callback_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libadsp_hvx_stub.so:system/vendor/lib/libadsp_hvx_stub.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_4K_preview.so:system/vendor/lib/libchromatix_chiron_imx386_semco_4K_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_4K_video.so:system/vendor/lib/libchromatix_chiron_imx386_semco_4K_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_common.so:system/vendor/lib/libchromatix_chiron_imx386_semco_common.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_hfr_120.so:system/vendor/lib/libchromatix_chiron_imx386_semco_cpp_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_hfr_60.so:system/vendor/lib/libchromatix_chiron_imx386_semco_cpp_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_hfr_90.so:system/vendor/lib/libchromatix_chiron_imx386_semco_cpp_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_liveshot.so:system/vendor/lib/libchromatix_chiron_imx386_semco_cpp_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_preview.so:system/vendor/lib/libchromatix_chiron_imx386_semco_cpp_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_snapshot.so:system/vendor/lib/libchromatix_chiron_imx386_semco_cpp_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_snapshot_hdr.so:system/vendor/lib/libchromatix_chiron_imx386_semco_cpp_snapshot_hdr.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_snapshot_hht.so:system/vendor/lib/libchromatix_chiron_imx386_semco_cpp_snapshot_hht.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_video.so:system/vendor/lib/libchromatix_chiron_imx386_semco_cpp_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_video_hdr.so:system/vendor/lib/libchromatix_chiron_imx386_semco_cpp_video_hdr.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_default_preview.so:system/vendor/lib/libchromatix_chiron_imx386_semco_default_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_default_video.so:system/vendor/lib/libchromatix_chiron_imx386_semco_default_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hdr_snapshot_3a.so:system/vendor/lib/libchromatix_chiron_imx386_semco_hdr_snapshot_3a.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hdr_video_3a.so:system/vendor/lib/libchromatix_chiron_imx386_semco_hdr_video_3a.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_120.so:system/vendor/lib/libchromatix_chiron_imx386_semco_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_120_3a.so:system/vendor/lib/libchromatix_chiron_imx386_semco_hfr_120_3a.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_60.so:system/vendor/lib/libchromatix_chiron_imx386_semco_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_60_3a.so:system/vendor/lib/libchromatix_chiron_imx386_semco_hfr_60_3a.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_90.so:system/vendor/lib/libchromatix_chiron_imx386_semco_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_90_3a.so:system/vendor/lib/libchromatix_chiron_imx386_semco_hfr_90_3a.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_liveshot.so:system/vendor/lib/libchromatix_chiron_imx386_semco_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_postproc.so:system/vendor/lib/libchromatix_chiron_imx386_semco_postproc.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_preview.so:system/vendor/lib/libchromatix_chiron_imx386_semco_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_snapshot.so:system/vendor/lib/libchromatix_chiron_imx386_semco_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_snapshot_hdr.so:system/vendor/lib/libchromatix_chiron_imx386_semco_snapshot_hdr.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_video.so:system/vendor/lib/libchromatix_chiron_imx386_semco_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_video_hdr.so:system/vendor/lib/libchromatix_chiron_imx386_semco_video_hdr.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_zsl_preview.so:system/vendor/lib/libchromatix_chiron_imx386_semco_zsl_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_zsl_video.so:system/vendor/lib/libchromatix_chiron_imx386_semco_zsl_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_a3_default_preview.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_a3_default_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_a3_default_video.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_a3_default_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_a3_hfr_120.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_a3_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_a3_hfr_60.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_a3_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_a3_hfr_90.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_a3_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_common.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_common.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_ds_chromatix.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_ds_chromatix.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_120.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_60.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_90.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_liveshot.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_preview.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_snapshot.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_us_chromatix.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_us_chromatix.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_video.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_video_full.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_video_full.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_default_video.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_default_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_hfr_120.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_hfr_60.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_hfr_90.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_liveshot.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_postproc.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_postproc.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_preview.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_snapshot.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_video_full.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_video_full.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_zsl_preview.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_zsl_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_zsl_video.so:system/vendor/lib/libchromatix_chiron_ov5675_primax_zsl_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_default_preview.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_default_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_default_video.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_default_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_120.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_60.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_90.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_common.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_common.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_ds_chromatix.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_ds_chromatix.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_120.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_60.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_90.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_liveshot.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_preview.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_snapshot.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_us_chromatix.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_us_chromatix.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_video.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_video_full.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_video_full.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_default_video.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_default_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_hfr_120.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_hfr_60.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_hfr_90.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_liveshot.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_postproc.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_postproc.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_preview.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_snapshot.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_video_full.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_video_full.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_zsl_preview.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_zsl_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_zsl_video.so:system/vendor/lib/libchromatix_chiron_ov5675_qtech_zsl_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_imx386_semco.so:system/vendor/lib/libmmcamera_chiron_imx386_semco.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_imx386_semco_eeprom.so:system/vendor/lib/libmmcamera_chiron_imx386_semco_eeprom.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_ov5675_primax.so:system/vendor/lib/libmmcamera_chiron_ov5675_primax.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_ov5675_primax_eeprom.so:system/vendor/lib/libmmcamera_chiron_ov5675_primax_eeprom.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_ov5675_qtech.so:system/vendor/lib/libmmcamera_chiron_ov5675_qtech.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_ov5675_qtech_eeprom.so:system/vendor/lib/libmmcamera_chiron_ov5675_qtech_eeprom.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/capi_v2_aptX_Classic.so:system/vendor/lib/rfsa/adsp/capi_v2_aptX_Classic.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/capi_v2_aptX_HD.so:system/vendor/lib/rfsa/adsp/capi_v2_aptX_HD.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/chiron-s/dirac_resource.dar:system/vendor/lib/rfsa/adsp/chiron-s/dirac_resource.dar \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/dirac_resource.dar:system/vendor/lib/rfsa/adsp/dirac_resource.dar \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/dirac_resource.so:system/vendor/lib/rfsa/adsp/dirac_resource.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libFastRPC_AUE_Forward_skel.so:system/vendor/lib/rfsa/adsp/libFastRPC_AUE_Forward_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libFastRPC_UTF_Forward_Qtc2_skel.so:system/vendor/lib/rfsa/adsp/libFastRPC_UTF_Forward_Qtc2_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libFastRPC_UTF_Forward_skel.so:system/vendor/lib/rfsa/adsp/libFastRPC_UTF_Forward_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libadsp_fd_skel.so:system/vendor/lib/rfsa/adsp/libadsp_fd_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libadsp_hvx_add_constant.so:system/vendor/lib/rfsa/adsp/libadsp_hvx_add_constant.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libadsp_hvx_skel.so:system/vendor/lib/rfsa/adsp/libadsp_hvx_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libapps_mem_heap.so:system/vendor/lib/rfsa/adsp/libapps_mem_heap.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libdirac-capiv2.so:system/vendor/lib/rfsa/adsp/libdirac-capiv2.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libexternal_dog_skel.so:system/vendor/lib/rfsa/adsp/libexternal_dog_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libhvxMathVIO.so:system/vendor/lib/rfsa/adsp/libhvxMathVIO.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libscveBlobDescriptor_skel.so:system/vendor/lib/rfsa/adsp/libscveBlobDescriptor_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libscveFaceLandmark_skel.so:system/vendor/lib/rfsa/adsp/libscveFaceLandmark_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libscveT2T_skel.so:system/vendor/lib/rfsa/adsp/libscveT2T_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libsns_low_lat_stream_skel.so:system/vendor/lib/rfsa/adsp/libsns_low_lat_stream_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libvpp_frc.so:system/vendor/lib/rfsa/adsp/libvpp_frc.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/rfsa/adsp/libvpp_svc_skel.so:system/vendor/lib/rfsa/adsp/libvpp_svc_skel.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/libadsp_default_listener.so:system/vendor/lib64/libadsp_default_listener.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/libfastcvadsp_stub.so:system/vendor/lib64/libfastcvadsp_stub.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/libfastcvopt.so:system/vendor/lib64/libfastcvopt.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/sensors.elliptic.so:system/vendor/lib64/sensors.elliptic.so
